services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    environment:
      SITE_ADDR: ${SITE_ADDR}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
  frontend:
    image: ghcr.io/prgrms-be-devcourse/nbe10-12-2-team04-frontend:latest
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION}
    depends_on:
      - backend
    restart: always

  backend:
    image: ghcr.io/prgrms-be-devcourse/nbe10-12-2-team04-backend:latest
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      LOG_DIR: ${LOG_DIR}
      IMAGE_UPLOAD: ${IMAGE_UPLOAD}
      SERVING_UPLOAD_PATH: ${SERVING_UPLOAD_PATH}
      THUMBNAIL_UPLOAD_PATH: ${THUMBNAIL_UPLOAD_PATH}
      PROFILE_UPLOAD_PATH: ${PROFILE_UPLOAD_PATH}
      PUBLIC_PREFIX: ${PUBLIC_PREFIX}
      IMAGE_FILE_SIZE: ${IMAGE_FILE_SIZE}
      MAX_IMAGE_FILES_SIZE: ${MAX_IMAGE_FILES_SIZE}
      ACCESS_TOKEN_EXPIRATION_SECONDS: ${ACCESS_TOKEN_EXPIRATION_SECONDS}
      REFRESH_TOKEN_EXPIRATION_SECONDS: ${REFRESH_TOKEN_EXPIRATION_SECONDS}
      THUMBNAIL_WIDTH: ${THUMBNAIL_WIDTH}
      THUMBNAIL_HEIGHT: ${THUMBNAIL_HEIGHT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend-images:${IMAGE_UPLOAD}
      - backend-logs:${LOG_DIR}
    restart: always

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  mysql-data:
  backend-images:
  backend-logs:
  caddy_data:
  caddy_config:
